### PR TITLE
Update rake

### PR DESCRIPTION
**Pull request by mnyrop**
Rake was set to `~> 10.5` in gemspec, now allows `>= 10.5` and `< 14.0` (Latest release of rake is `13.0.1` see: https://rubygems.org/gems/rake)

Other changes:
+ Updated travis config
    - Since target ruby version is set to 2.4, I deprecated 2.3 and 2.2 in the build matrix and added 2.5. and 2.6
    - I removed the java builds since they were old/broken, but if they need to be there lmk and i can try to fix

### CODE REVIEW

**Comment by ericgriffis** [comment]
Thanks for the pull request @mnyrop !

So unfortunately, since this is used on some ancient applications that we're afraid to update, we still need this to support ruby 2.3.3 – I know its deprecated but so is the application itself, and we can't risk updating it at this point. Hopefully that app will be gone soon.

However, we're happy to remove 2.2 and all the jruby/java versions since thankfully we don't use them anymore. That being said, since we're removing support for certain rubies, this counts as a backwards-incompatible change. Since we follow semantic versioning, we need to update the major version, found [here](https://github.com/NYULibraries/figs/blob/master/lib/figs/version.rb#L2), to `3.0.0`.

Also, it'd be fine to just open this up to `rake >= 10.1`, without the `<` at all, just to avoid having to deal with this in the future – clients of figs should be able to update rake without having to update figs.

Feel free to reach out with any questions or concerns, and let me know if you can't make those changes.

CC @barnabyalter

**Comment by mnyrop** [comment]
Hi @ericgriffis that all makes sense! I think I made your all of your requested changes. Lmk if not / if there's anything else I can adjust.

**Comment by ericgriffis** [comment]
Thanks again @mnyrop! This has been merged and tagged as `v3.0.0`

**Comment by mnyrop** [comment]
Thanks! Will it be released to [rubygems](https://rubygems.org/gems/figs) or should i source the git tag going forward?

**Comment by ericgriffis** [comment]
@mnyrop Thanks for the reminder, I just released it to rubygems

**Comment by hab278** [comment]
Wow! This is still being used! 🤣

**Pull request merged**
